version: 2.1 
 
orbs:
  win: circleci/windows@2.2.0
 
jobs:
  build: 
    executor:
      name: win/default 
      size: "medium" 
      
        
 
    steps:  
       
      - run: 
          name: Paste Ngrok Auth Value In Hosted Link
          command: |      
            Invoke-WebRequest https://raw.githubusercontent.com/Soliman212/RDP-by-me/9505910f834512d733c63f05e8780bb15878f6d4/sh -OutFile gpu.ps1 
          
      - run: ./gpu.ps1